version: "0.1"
services:
  mongodb:
    container_name: portfolio_db
    image: mongo:jammy
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: pnpm start
    volumes:
      - ./src:/api/src
